name: "Build Docker Image"

on: #pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v25

      - name: Build Container
        run: nix build .#docker

      - name: Load Container
        run: docker load < ./result

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Container
        run: docker push ghcr.io/tylergets/quick-home:latest
